using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DoAn_LTQLUD.BUS;

namespace DoAn_LTQLUD
{
    public partial class frmMuaHang : DevExpress.XtraEditors.XtraForm
    {
        public frmMuaHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DoAn_LTQLUD.PerfectAppEntities dbContext = new DoAn_LTQLUD.PerfectAppEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.PhieuTemps.LoadAsync().ContinueWith(loadTask =>
            {
            // Bind data to control when loading complete
            phieuTempsBindingSource.DataSource = dbContext.PhieuTemps.Local.ToBindingList();
                    }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            

            repositoryItemGridLookUpEdit6.DataSource = HangHoaBUS.DanhSach();
            repositoryItemGridLookUpEdit6.NullText = "";
            repositoryItemGridLookUpEdit6.DisplayMember = "TenHang";
            repositoryItemGridLookUpEdit6.ValueMember = "MaHang";

            repositoryItemGridLookUpEdit7.DataSource = DonViBUS.DanhSach();
            repositoryItemGridLookUpEdit7.NullText = "";
            repositoryItemGridLookUpEdit7.DisplayMember = "Ten";
            repositoryItemGridLookUpEdit7.ValueMember = "MaDV";

            txtNCC.Properties.DataSource = NhaCungCapBUS.DanhSach();
            txtNCC.Properties.DisplayMember = "TenNCC";
            txtNCC.Properties.ValueMember = txtMaNCC.Properties.ValueMember;
            txtNCC.Properties.EditValueChanged += Properties_EditValueChanged;
            txtNCC.Properties.NullText = "";

            txtMaNCC.Properties.DataSource = NhaCungCapBUS.DanhSach();
            txtMaNCC.Properties.DisplayMember = "MaNCC";
            txtMaNCC.Properties.ValueMember = "MaNCC";
            txtMaNCC.Properties.EditValueChanged += Properties_EditValueChanged1;
            txtMaNCC.Properties.NullText = "";

            txtPhieu.Text = PhieuNhapHangBUS.LayMaPhieu();

            txtNhanVien.Properties.DataSource = NhanVienBUS.DanhSach();
            txtNhanVien.Properties.DisplayMember = "Ten";
            txtNhanVien.Properties.ValueMember = "MaNV";

            txtDieuKhoanTT.Properties.DataSource = DieuKhoanTTBUS.DanhSach();
            txtDieuKhoanTT.Properties.DisplayMember = "TenDKTT";
            txtDieuKhoanTT.Properties.ValueMember = "MaDKTT";

            txtHinhThucTT.Properties.DataSource = HinhThucTTBUS.DanhSach();
            txtHinhThucTT.Properties.DisplayMember = "TenHTTT";
            txtHinhThucTT.Properties.ValueMember = "MaHTTT";

            txtKho.Properties.DataSource = KhoBUS.DanhSach();
            txtKho.Properties.DisplayMember = "Ten";
            txtKho.Properties.ValueMember = "MaKho";
        }

        private void ClearAllTxt()
        {
            txtMaNCC.Text = null;
            txtNCC.Text = null;
            txtDiaChi.Text = null;
            txtDienThoai.Text = null;
            txtDieuKhoanTT.Text = null;
            txtGhiChu.Text = null;
            txtHinhThucTT.Text = null;
            txtHoaDonVAT.Text = null;
            txtKho.Text = null;
            txtNhanVien.Text = null;
            txtPhieu.Text = PhieuNhapHangBUS.LayMaPhieu();
            txtPhieuVietTay.Text = null;
            Ngay.Text = null;
            HanTT.Text = null;

            DoAn_LTQLUD.PerfectAppEntities dbContext = new DoAn_LTQLUD.PerfectAppEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.PhieuTemps.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                phieuTempsBindingSource.DataSource = dbContext.PhieuTemps.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void Properties_EditValueChanged1(object sender, EventArgs e)
        {
            int vitri = txtMaNCC.Properties.GetIndexByKeyValue(txtMaNCC.EditValue);
            txtNCC.EditValue = txtNCC.Properties.GetKeyValue(vitri);
        }

        private void Properties_EditValueChanged(object sender, EventArgs e)
        {
            int vitri = txtNCC.Properties.GetIndexByKeyValue(txtNCC.EditValue);
            txtMaNCC.EditValue = txtMaNCC.Properties.GetKeyValue(vitri);
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            PhieuNhapHangBUS.Them(txtPhieu.Text, txtMaNCC.EditValue.ToString(), txtDiaChi.Text, txtDienThoai.Text, Ngay.DateTime, txtGhiChu.Text, txtHoaDonVAT.Text, txtPhieuVietTay.Text, txtNhanVien.EditValue.ToString(), txtKho.EditValue.ToString(), txtDieuKhoanTT.EditValue.ToString(), txtHinhThucTT.EditValue.ToString(), HanTT.DateTime);
            for(int i = 0;i<gridView2.RowCount - 1; i++)
            {
                string MaHang = gridView2.GetRowCellValue(i, "TenHang").ToString();
                string MaDonVi = gridView2.GetRowCellValue(i, "TenDonVi").ToString();
                int SoLuong = (int)gridView2.GetRowCellValue(i, "SoLuong");
                double DonGia = (double)gridView2.GetRowCellValue(i, "DonGia");
                string GhiChu = gridView2.GetRowCellValue(i, "GhiChu").ToString();
                ChiTietPhieuNhapHangBUS.Them(txtPhieu.Text, MaHang, MaDonVi, SoLuong, DonGia, GhiChu);
            }
            ClearAllTxt();
        }
    } 
}