using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace DoAn_LTQLUD
{
    public partial class frmMuaHang : DevExpress.XtraEditors.XtraForm
    {
        public frmMuaHang()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DoAn_LTQLUD.PerfectAppEntities dbContext = new DoAn_LTQLUD.PerfectAppEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.PhieuTemps.Load();
            // Bind data to control when loading complete
            gridControl1.DataSource = dbContext.PhieuTemps.Local.ToBindingList();
        } 
        
    } 
}