//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTQLUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.MaVaches = new HashSet<MaVach>();
            this.ChiTietPhieuNhapHangs = new HashSet<ChiTietPhieuNhapHang>();
        }
    
        public string MaHang { get; set; }
        public string MaLoaiHangHoa { get; set; }
        public string MaKho { get; set; }
        public string MaPhanLoai { get; set; }
        public string TenHang { get; set; }
        public string MaDV { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> TonKhoToiThieu { get; set; }
        public Nullable<int> TonHienTai { get; set; }
        public string Anh { get; set; }
        public string MaVachNSX { get; set; }
        public string MaNCC { get; set; }
        public Nullable<double> GiaMua { get; set; }
        public Nullable<double> GiaBanSi { get; set; }
        public Nullable<double> GiaBanLe { get; set; }
        public Nullable<int> ConQuanLy { get; set; }
    
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual KhoHang KhoHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhomHang NhomHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaVach> MaVaches { get; set; }
        public virtual NhomHang NhomHang1 { get; set; }
        public virtual PhanLoaiHangHoa PhanLoaiHangHoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapHang> ChiTietPhieuNhapHangs { get; set; }
    }
}
