//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTQLUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.HangHoas = new HashSet<HangHoa>();
            this.PhieuNhapHangs = new HashSet<PhieuNhapHang>();
        }
    
        public string MaNCC { get; set; }
        public string MaKhuVuc { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaSoThue { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<int> GioiHanNo { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public string NganHang { get; set; }
        public Nullable<int> NoHienTai { get; set; }
        public string ChucVu { get; set; }
        public string NguoiLienHe { get; set; }
        public Nullable<int> ConQuanLy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHang> PhieuNhapHangs { get; set; }
    }
}
