//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTQLUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.KhoHangs = new HashSet<KhoHang>();
            this.NhanVien1 = new HashSet<NhanVien>();
            this.PhieuNhapHangs = new HashSet<PhieuNhapHang>();
        }
    
        public string MaNV { get; set; }
        public string Ten { get; set; }
        public Nullable<int> ConQuanLy { get; set; }
        public string ChucVu { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<int> DienThoai { get; set; }
        public Nullable<int> DiDong { get; set; }
        public string MaBP { get; set; }
        public string MaNVQL { get; set; }
    
        public virtual BoPhanNhanVien BoPhanNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoHang> KhoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHang> PhieuNhapHangs { get; set; }
    }
}
