//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTQLUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyGia
    {
        public string MaTyGia { get; set; }
        public string TenTyGia { get; set; }
        public Nullable<double> TyGiaQuyDoi { get; set; }
        public Nullable<int> ConQuanLy { get; set; }
    }
}
